language: node_js
node_js:
- '8'
before_script:
  - > 
    docker run --name rabbitmq  \
      --detach \
      --publish 5672:5672 \
      --environment RABBITMQ_PID_FILE=/pid \
      rabbitmq:alpine
  - docker exec rabbitmq rabbitmqctl wait /pid